main: red.kalos.morefish.MoreFish
name: KalosMoreFish
version: ${project.version}
authors:
  - Red_Carl
website: https://github.com/RedCarl/KalosMoreFish
softdepend: [Vault, ProtocolLib]
commands:
  morefish:
    description: MoreFish 的主要命令.
    usage: /morefish
    aliases: [mf, fish]
permissions:
  morefish.admin:
    default: op
    description: Morefish的管理权限.
  morefish.help:
    default: true
    description: Morefish的Help命令权限 ( /morefish help ).
  morefish.top:
    default: true
    description: Morefish的Top命令权限 ( /morefish top ).
  morefish.shop:
    default: op
    description: Morefish的Shop命令权限 ( /morefish Shop ).